import "~/styles/globals.css";
import "@uploadthing/react/styles.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { TopNav } from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { CSPostHogProvider } from "./_analytics/provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "PENIN - Pensamientos Intrusivos",
  description:
    "Generated by a loyal suscriber by theo on youtube and making his own t3 app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <CSPostHogProvider>
        <html lang="es">
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <body
            className={`font-sans ${inter.variable} flex flex-col gap-4 bg-neutral-100 text-neutral-900`}
          >
            <div className="grid h-screen grid-rows-[auto,1fr]">
              <TopNav />
              <main className="mx-auto mt-9 w-full max-w-screen-xl overflow-y-scroll">
                {children}
              </main>
            </div>
          </body>
        </html>
      </CSPostHogProvider>
    </ClerkProvider>
  );
}
