import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { GeistSans } from "geist/font/sans";
import { extractRouterConfig } from "uploadthing/server";
import { TailwindIndicator } from "~/components/tailwind-indicator";
import { cn } from "~/lib/utils";
import { CSPostHogProvider } from "./_analytics/provider";
import { SideNav } from "./_components/side-nav";
import { ourFileRouter } from "./api/uploadthing/core";
import { FloatingNav } from "./_components/floating-nav";
import { Mali } from "next/font/google";

export const metadata = {
	title: "PENIN - Pensamientos Intrusivos",
	description:
		"Generated by a loyal suscriber by theo on youtube and making his own t3 app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = Mali({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	display: "swap",
	variable: "--font-mali",
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<CSPostHogProvider>
				<html lang="es">
					<NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
					<body
						className={cn("font-sans", GeistSans.variable, fontSans.variable)}
						style={{ scrollbarColor: "rgb(185, 202, 211) rgb(247, 249, 249)" }}
					>
						<div className="absolute inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]">
							<div className="absolute left-0 right-0 top-0 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-green-400 opacity-20 blur-[100px]" />
						</div>
						<div className="css-175 pointer-events-none [flex:1_1_0%]">
							<div className="css-175 pointer-events-auto z-0 min-h-dvh w-full flex-row">
								<SideNav />
								<FloatingNav />
								<main className="css-175 w-full shrink grow items-start overflow-y-scroll">
									{children}
								</main>
							</div>
						</div>
						<TailwindIndicator />
					</body>
				</html>
			</CSPostHogProvider>
		</ClerkProvider>
	);
}
